apiVersion: v1
kind: Service
metadata:
  name: simple-node-service
spec:
  type: NodePort
  selector:
    app: simple-node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
